// File: ui/theme/Color.kt
package com.example.cosmeticlumea.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val LightPrimary = Color(0xFFFF0066)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFD9E2)
val LightOnPrimaryContainer = Color(0xFF3F001D)
val LightSecondary = Color(0xFFD32F2F)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFDAD6)
val LightOnSecondaryContainer = Color(0xFF410002)
val LightTertiary = Color(0xFF7A5900)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDE91)
val LightOnTertiaryContainer = Color(0xFF261900)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF000000)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF000000)
val LightSurfaceVariant = Color(0xFFE0E0E0)
val LightOnSurfaceVariant = Color(0xFF424242)
val LightOutline = Color(0xFFBDBDBD)

// Dark Theme Colors
val DarkPrimary = Color(0xFFFF0066)
val DarkOnPrimary = Color(0xFFFFFFFF)
val DarkPrimaryContainer = Color(0xFF9E004A)
val DarkOnPrimaryContainer = Color(0xFFFFD9E2)
val DarkSecondary = Color(0xFFEFB8C8)
val DarkOnSecondary = Color(0xFF472A30)
val DarkSecondaryContainer = Color(0xFF603F46)
val DarkOnSecondaryContainer = Color(0xFFFFDAD6)
val DarkTertiary = Color(0xFFFAD14A)
val DarkOnTertiary = Color(0xFF402D00)
val DarkTertiaryContainer = Color(0xFF5D4300)
val DarkOnTertiaryContainer = Color(0xFFFFDE91)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF000000)
val DarkOnBackground = Color(0xFFFFFFFF)
val DarkSurface = Color(0xFF000000)
val DarkOnSurface = Color(0xFFFFFFFF)
val DarkSurfaceVariant = Color(0xFF2E2E2E)
val DarkOnSurfaceVariant = Color(0xFFB0B0B0)
val DarkOutline = Color(0xFF616161)

// Custom
val OnboardingScreenBackground = Color(0xFFFDE4E6)
val AuthScreenBackground = Color(0xFFFDE4E6)
